### ISSUE TITLE
HixDS18B20 class with many Dallas termometers

### ISSUE THREAD

**Issue by pstolarz** [hixfield/HixArduino#1]
Hi @hixfield and thanks for testing my lib on ESP8266 platform. I hope it works fine. Did you have troubles with `OneWire` lib that you decided to use mine?

I see one issue with using `HixDS18B20` with more than 1 thermometer - it will simply not work if more than 1 therm will be connected to the bus.

1. `HixDS18B20::begin()` will return `false` (error), since OneWireNg::search() will return `OneWireNg::EC_MORE` in this case:

```C
  ec = m_pOneWire->search(m_sensorId);
  return ec == OneWireNg::EC_DONE;
```

Of course this shouldn't be treated as an error. It simply informs the caller - more devices are available to fetch, call me more to get their ids...

2. Why constraint to only single connected therm? Don't you think this simplification goes too far. You may have implemented search routine returning all Dallas therms supported by your lib (using family code filtering) and then use `getTemp()` to fetch temperature for a given id. There is also possible to send `CONVERT_T` to all devs connected via `OneWireNg::addressAll()` and next read the result on-by-one. This dramatically reduces the read operation time and gives temperature at a given moment of time measured at all devices simultaneously.

Thanks,
Piotrek

**Comment by hixfield** [comment]
Thanks for the feedback and suggestions. Until now I have not yet had the need to support multiple sensors, but I’ll keep it in mind. Yes, I had issues with the ds18b20 not working on de ESP, with your lib it works.

**Comment by MHz000** [comment]
Hi hixfield
I has trouble too with the "standard" arduino 1-wire lib on ESP-platform - may be caused by my limited knowledge I admit. Testing the onewireNG lib on a ESP-01 compiles fine but crashed on runtime. In your comment to Piotrek you wrote "with your lib it works". Have you any idea what do I miss in my setup? I use the unmodified DS18B20 example attached to the -NG lib.
My goal is deploy an ESP-01 with it 2 GPIOs for management/supervising a solar power station by a DS2438 chip.
Thank you for any suggestion
Jochen

**Comment by pstolarz** [comment]
@MHz000 I probably found source of the problem. https://github.com/pstolarz/OneWireNg/issues/2 helped me a lot. It reveals on 8266 platform only. Will be fixed soon.
